Store all meta-information in database
Shkaolin/BERTopic-as-service pull request #7
Opened 2021-11-04 18:31 UTC by AlexeyVatolin

2021-11-04 18:56 UTC, SergeyShk commented on Makefile
> +mypy: ## Check sorting with black
Check typing with mypy

2021-11-05 13:11 UTC, SergeyShk requested changes

2021-11-05 13:18 UTC, AlexeyVatolin commented on service/api/endpoints/model_training.py
> +from service.models import models
I think by the name of the class it is unclear whether it is a table in the database or just pydantic class

2021-11-05 13:29 UTC, AlexeyVatolin commented on service/db/db.py
> +from service.models import models  # NOQA
Otherwise, sqlmodel does not find model classes because the module is not scanned (imported)

2021-11-05 13:44 UTC, AlexeyVatolin commented on service/db/db.py
> +from service.models import models  # NOQA
Tested, if I remove this import, the tables are not created at the start of the project

2021-11-05 14:18 UTC, SergeyShk approved these changes

2021-11-05 15:22 UTC, merged